import { NextRequest, NextResponse } from "next/server";
import { env } from "cloudflare:workers";
import { clearSession, createSession, currentUser, hashPin } from "@/lib/auth";
import { ensureSeeded } from "@/lib/seed";
export const dynamic="force-dynamic";
const bad=(message:string,status=400)=>NextResponse.json({error:message},{status});
async function state(){const user=await currentUser();if(!user)return {user:null};const members=await env.DB.prepare(`SELECT m.id,m.name,m.email,m.role,m.active,COALESCE(SUM(c.amount),0) contributions FROM members m LEFT JOIN contributions c ON c.member_id=m.id GROUP BY m.id ORDER BY m.name`).all();const loans=await env.DB.prepare(`SELECT l.*,m.name member_name FROM loan_transactions l JOIN members m ON m.id=l.member_id ORDER BY l.date DESC,l.id DESC`).all();const contributions=await env.DB.prepare(`SELECT c.*,m.name member_name FROM contributions c JOIN members m ON m.id=c.member_id ORDER BY c.date DESC,c.id DESC`).all();const bank=await env.DB.prepare("SELECT value FROM settings WHERE key='bank_balance'").first<{value:string}>();return {user,members:members.results,loans:loans.results,contributions:contributions.results,bankBalance:Number(bank?.value||0)}}
export async function GET(){await ensureSeeded();return NextResponse.json(await state())}
export async function POST(req:NextRequest){await ensureSeeded();const b=await req.json();if(b.action==="login"){const email=String(b.email||"").trim().toLowerCase(),pin=String(b.pin||"");const row=await env.DB.prepare("SELECT id,pin_hash FROM members WHERE lower(email)=? AND active=1").bind(email).first<{id:number;pin_hash:string}>();if(!row||row.pin_hash!==await hashPin(email,pin))return bad("Email or PIN is incorrect.",401);await createSession(row.id);return NextResponse.json(await state())}if(b.action==="logout"){await clearSession();return NextResponse.json({ok:true})}const user=await currentUser();if(!user)return bad("Please sign in again.",401);if(user.role!=="admin")return bad("Only the admin can make changes.",403);const now=new Date().toISOString();if(b.action==="add_contribution")await env.DB.prepare("INSERT INTO contributions(member_id,date,amount,note,created_at,updated_at) VALUES(?,?,?,?,?,?)").bind(Number(b.memberId),b.date,b.amount===""?null:Number(b.amount),b.note||null,now,now).run();else if(b.action==="add_loan"){const principal=b.type==="loan"?Number(b.principal):null,term=b.type==="loan"?Number(b.term):null,interest=b.type==="loan"?principal*term*0.03:null,total=b.type==="loan"?principal+interest:Number(b.amount);let due=null;if(b.type==="loan"){const d=new Date(`${b.date}T00:00:00Z`);d.setUTCMonth(d.getUTCMonth()+term);due=d.toISOString().slice(0,10)}await env.DB.prepare("INSERT INTO loan_transactions(member_id,date,type,principal,term_months,interest,amount,due_date,status,note,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)").bind(Number(b.memberId),b.date,b.type,principal,term,interest,total,due,b.status||"open",b.note||null,now,now).run()}else if(b.action==="save_member"){const id=Number(b.memberId),email=String(b.email||"").trim().toLowerCase()||null,pin=String(b.pin||"");if(email&&pin)await env.DB.prepare("UPDATE members SET email=?,pin_hash=?,role=?,active=? WHERE id=?").bind(email,await hashPin(email,pin),b.role||"member",b.active?1:0,id).run();else await env.DB.prepare("UPDATE members SET email=?,role=?,active=? WHERE id=?").bind(email,b.role||"member",b.active?1:0,id).run()}else if(b.action==="bank")await env.DB.prepare("UPDATE settings SET value=? WHERE key='bank_balance'").bind(String(Number(b.amount)||0)).run();else if(b.action==="delete"){const table=b.kind==="contribution"?"contributions":"loan_transactions";await env.DB.prepare(`DELETE FROM ${table} WHERE id=?`).bind(Number(b.id)).run()}else return bad("Unknown action");return NextResponse.json(await state())}
